/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
  java
}

repositories {
  // Use Maven Central for resolving dependencies
  mavenCentral()
  // Define the PaperMC maven repository
  maven {
    name = "papermc"
    url = uri("https://repo.papermc.io/repository/maven-public")
  }
}

dependencies {
  // Use JUnit test framework
  testImplementation(libs.junit)
  // This dependency is used by the application
  implementation(libs.guava)
  // Paper API
  compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
}

// Apply a specific Java toolchain to ease working on different environments
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

tasks {
  jar {
    archiveFileName.set(project.name + "-bukkit-" + project.version + ".jar")
  }
}
